# Generated by Django 4.2 on 2023-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_content_lesson_remove_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='short_description',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
