# Generated by Django 4.2 on 2023-04-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_contents_lesson_additional_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='identifier',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='additional_content',
            field=models.ManyToManyField(blank=True, to='course.content'),
        ),
    ]
