# Generated by Django 4.2 on 2023-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lesson_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='identifier',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
