# Generated by Django 4.2 on 2023-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_content_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.CharField(max_length=30, unique='true'),
        ),
    ]
