# Generated by Django 4.2 on 2023-04-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_quizorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizOrder',
        ),
    ]
