# Generated by Django 4.2 on 2023-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_quizorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='additional_content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_order',
            field=models.ManyToManyField(blank=True, to='course.quizorder'),
        ),
        migrations.AlterField(
            model_name='quizorder',
            name='identifier',
            field=models.CharField(max_length=30, unique='true'),
        ),
        migrations.AlterField(
            model_name='quizorder',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
