# Generated by Django 4.2 on 2023-04-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_lesson_additional_content_lesson_quiz_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='quiz_order',
            new_name='quiz_order_list',
        ),
    ]
