# Generated by Django 4.2 on 2023-04-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_enrolledlesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrolledLesson',
        ),
    ]
