# Generated by Django 4.2 on 2023-04-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_delete_enrolledlesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
    ]
