# Generated by Django 4.2 on 2023-04-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_remove_lesson_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizorder',
            old_name='text_area',
            new_name='quiz_description',
        ),
    ]
