# Generated by Django 4.2 on 2023-04-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_rename_text_area_quizorder_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quiz_order_list',
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_order_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.quizorder'),
        ),
    ]
