# Generated by Django 4.2 on 2023-04-29 17:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0025_sortingquiz_correctanswerquiz_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortingQuiz',
            new_name='QuizOrder',
        ),
    ]
