# Generated by Django 4.2 on 2023-04-29 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0026_rename_sortingquiz_quizorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizOrder',
            new_name='SortingQuiz',
        ),
        migrations.AlterModelOptions(
            name='correctanswerquiz',
            options={'verbose_name_plural': 'Correct Answer Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='sortingquiz',
            options={'verbose_name_plural': 'Sorting Quizzes'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='quiz_order',
            new_name='sorting_quiz',
        ),
        migrations.AddField(
            model_name='lesson',
            name='correct_answer_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.correctanswerquiz'),
        ),
    ]
