# Generated by Django 4.2 on 2023-04-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_rename_quizorder_sortingquiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctanswerquiz',
            options={'verbose_name_plural': 'Quiz: Correct Answer'},
        ),
        migrations.AlterModelOptions(
            name='sortingquiz',
            options={'verbose_name_plural': 'Quiz: Sorting'},
        ),
    ]
