# Generated by Django 4.2 on 2023-04-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_lesson_quiz_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quiz_type',
        ),
    ]
