# Generated by Django 4.2 on 2023-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_remove_lesson_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
