# Generated by Django 4.2 on 2023-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_alter_sortingquiz_element1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortingquiz',
            name='element1',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sortingquiz',
            name='element2',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sortingquiz',
            name='element3',
            field=models.TextField(max_length=300),
        ),
    ]
