# Generated by Django 4.2 on 2023-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_alter_category_options_category_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='my_order',
            new_name='order',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
