# Generated by Django 4.2 on 2023-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_alter_category_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
