# Generated by Django 4.2 on 2023-05-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_alter_course_options_course_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
