# Generated by Django 4.2 on 2023-05-09 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0042_alter_category_options_remove_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTextQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('quiz_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published')], default='draft', max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('correctAnswer1', models.TextField(max_length=150)),
                ('correctAnswer2', models.TextField(blank=True, max_length=150, null=True)),
                ('correctAnswer3', models.TextField(blank=True, max_length=150, null=True)),
                ('correctAnswer4', models.TextField(blank=True, max_length=150, null=True)),
                ('correctAnswer5', models.TextField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quiz: Free Text',
            },
        ),
    ]
