# Generated by Django 4.2 on 2023-05-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0044_lesson_free_text_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/lesson_images')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='course.lessonimage'),
        ),
    ]
