# Generated by Django 4.2 on 2023-05-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_lessonimage_lesson_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='images',
            field=models.ManyToManyField(blank=True, to='course.lessonimage'),
        ),
    ]
