# Generated by Django 4.2 on 2023-05-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_alter_lesson_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='images',
        ),
        migrations.AddField(
            model_name='lesson',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson_images'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson_images'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson_images'),
        ),
        migrations.DeleteModel(
            name='LessonImage',
        ),
    ]
