# Generated by Django 4.2 on 2023-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0047_remove_lesson_images_lesson_image1_lesson_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
