# Generated by Django 4.2 on 2023-05-12 08:57

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0048_alter_lesson_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson_images', validators=[course.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson_images', validators=[course.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lesson_images', validators=[course.validators.validate_file_size]),
        ),
    ]
