# Generated by Django 4.2 on 2023-05-12 14:23

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0051_alter_lesson_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/course_images', validators=[course.validators.validate_file_size]),
        ),
    ]
