# Generated by Django 4.2 on 2023-05-12 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0052_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('quiz_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published')], default='draft', max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('answer1', models.TextField(max_length=150)),
                ('solution1', models.BooleanField()),
                ('answer2', models.TextField(max_length=150)),
                ('solution2', models.BooleanField()),
                ('answer3', models.TextField(max_length=150)),
                ('solution3', models.BooleanField()),
                ('answer4', models.TextField(max_length=150)),
                ('solution4', models.BooleanField()),
                ('answer5', models.TextField(max_length=150)),
                ('solution5', models.BooleanField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quiz: Multiple Choice',
            },
        ),
    ]
